---
title: "Plot Within vs. Between ISC for different ROIs"
output: html_document
---
```{r echo = FALSE, warning=FALSE, message=FALSE}
######################################################################## 
#                               Load Packages                          #
########################################################################
library(plyr)
library(tidyverse)
library(ggpubr)
library(car)
library(Hmisc) 
library(lme4) 
library(lmerTest)  
library(cowplot)

###################### Script Specific Functions #######################
asNumeric <- function(x) as.numeric(as.character(x))
factorsNumeric <- function(d) modifyList(d, lapply(d[, sapply(d, is.factor)],   
                                                   asNumeric))
sem <- 
  function(x) {sd(x,na.rm = T) / sqrt(length(x))}

myPalette <- c("#4daf4a","#984ea3","#984ea3")
```

```{r load_data}
######################################################################## 
#                       Load and preprocess data                       #
########################################################################
# load data
d0 = read.csv("../../data/fmri/movie_data/wb_roi/WB_regional.csv")
d0$Subject = factor(d0$Subject)

d1 = gather(d0, type, r, 4:5)
d1$roi = factor(d1$roi, levels = c('A1','V1','DMPFC'))
d1$type = factor(d1$type, levels = c('within','between'))

```

#### Plot within and between group similarity separately for A1, V1 and DMPFC
```{r echo = FALSE, warning=FALSE, message=FALSE, fig.width=6, fig.height=3, fig.align='center'}
GroupData = d1 %>% 
  group_by(roi, type) %>%
  dplyr::summarise(avg_r = mean(r), sem_r = sem(r))

ggplot(d1, aes(x = type, y = r, color = type, group = Subject)) +
  geom_bar(aes(x = type, y = avg_r, group = NULL),
           data = GroupData,
           stat = "identity",
           fill="white",
           width = 0.3,
           size = 1.2) +
  geom_point(size = 3, alpha = 0.2) +
  geom_line(color = 'black', size = 1, alpha = 0.2) +
  geom_errorbar(aes(x = type, y = avg_r, ymin = avg_r-sem_r, ymax = avg_r+sem_r, color = type, group = NULL),
                data = GroupData,
                width = 0.2, size = 1) + 
  facet_wrap( ~ roi, ncol = 3) +
  scale_color_manual(values = myPalette) +
  theme(legend.position="none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=12,color="black"),
        axis.text.y  = element_text(size=12,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        title = element_text(size=16),
        strip.text.x = element_text(size = 14)) +
  coord_cartesian(ylim = c(0,0.34))

```

#### t-tests
```{r}
t.test(r ~ type, data = subset(d1, roi == "A1"), paired = TRUE)
t.test(r ~ type, data = subset(d1, roi == "V1"), paired = TRUE)
t.test(r ~ type, data = subset(d1, roi == "DMPFC"), paired = TRUE)
```

### Figure S2
```{r fig.width=4, fig.height=3}
GroupDataOrientation = d1 %>% 
  group_by(roi, orientation, type) %>%
  dplyr::summarise(avg_r = mean(r), sem_r = sem(r))


ggplot(subset(d1, roi == "DMPFC"), aes(x = type, y = r, color = type, group = Subject)) +
  geom_bar(aes(x = type, y = avg_r, group = NULL),
           data = subset(GroupDataOrientation, roi == "DMPFC"),
           stat = "identity",
           fill="white",
           width = 0.3,
           size = 1.2) +
  geom_point(size = 3, alpha = 0.2) +
  geom_line(color = 'black', size = 1, alpha = 0.2) +
  geom_errorbar(aes(x = type, y = NULL, ymin = avg_r-sem_r, ymax = avg_r+sem_r, color = type, group = NULL),
                data = subset(GroupDataOrientation, roi == "DMPFC"),
                width = 0.2, size = 1) + 
  scale_color_manual(values = myPalette) +
  theme(legend.position="none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=12,color="black"),
        axis.text.y  = element_text(size=12,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        title = element_text(size=16),
        strip.text.x = element_text(size = 14)) +
  coord_cartesian(ylim = c(0,0.34)) +
  facet_wrap(~ orientation)
```

```{r}
dDMPFC = subset(d1, roi == "DMPFC")

# T-test 
t.test(r ~ type, data = subset(dDMPFC, orientation == "Conservative"), paired = TRUE)
t.test(r ~ type, data = subset(dDMPFC, orientation == "Liberal"), paired = TRUE)


# Interaction effect
summary(lmer(r ~ type * orientation + (1|Subject), data = dDMPFC))

```

