---
title: "Attitude Change"
output: html_document
---

```{r load_libraries, echo = F, warning=FALSE, message=FALSE}
rm(list=ls())

# Load packages
library(tidyr)
library(dplyr)
library(ggplot2)
library(lmerTest)
library(cowplot)
library(MASS)
library(sfsmisc)
library(Rarity)

# Script Specific Functions
asNumeric <- function(x) as.numeric(as.character(x))
factorsNumeric <- function(d) modifyList(d, lapply(d[, sapply(d, is.factor)],   
                                                   asNumeric))
sem <- 
  function(x) {sd(x,na.rm = T) / sqrt(length(x))}

myPalette <- c("#4C72B0", "#C44E52")

```

### Load behavioral data and reverse code
```{r}
# load video ratings
AllData = read.csv("../../data/behav/VideoRating.csv")

AllData$AgreeRecode = ifelse(AllData$ReverseCode_Video == 2, 
                             AllData$Agree,
                             6 - AllData$Agree)

AllData$CredRecode = ifelse(AllData$ReverseCode_Video == 2, 
                             AllData$Credible,
                             6 - AllData$Credible)

AllData$ChangeRecode = ifelse(AllData$ReverseCode_Issue == 2, 
                             AllData$Change,
                             6 - AllData$Change)
```

#### Add in neural measure
```{r message=F}
NeuralDiff = read.csv('../../data/fmri/roi_tc/DMPFC/DMPFC_VideoNeural.csv', header = F)

colnames(NeuralDiff) = c('Subj','Video','LibSim','ConSim','Lib_Con')
NeuralDiff$Con_Lib = -NeuralDiff$Lib_Con

AllData = full_join(AllData, NeuralDiff)

AllData$Subj = factor(AllData$Subj)
```


#### Change by group
```{r}
SubjData = AllData %>% 
  group_by(Subj,Group) %>%
  dplyr::summarise(ChangeRecode = mean(ChangeRecode))

GroupData = SubjData %>%
  group_by(Group) %>%
  dplyr::summarise(meanChangeRecode = mean(ChangeRecode), SE = sem(ChangeRecode))

t.test(ChangeRecode ~ Group, SubjData)
```

#### Plot Fig S6
```{r fig.height = 4, fig.width = 4}
SubjData$Group = factor(SubjData$Group,levels= c("Liberal", "Conservative"))
GroupData$Group = factor(GroupData$Group, levels= c("Liberal", "Conservative"))

t_shift <- scales::trans_new("shift",
                             transform = function(x) {x-1},
                             inverse = function(x) {x+1})

ggplot(SubjData, aes(x = Group, y = ChangeRecode, color = Group)) +
  geom_bar(aes(x = Group, y = meanChangeRecode),
           data = GroupData,
           stat = "identity",
           fill="white",
           width = 0.3,
           size = 1.5) +
  geom_errorbar(aes(x = Group, y = NULL, ymin = meanChangeRecode-SE, ymax = meanChangeRecode+SE, color = Group),
                data = GroupData,
                width = 0.2) + 
  geom_point(alpha = 0.75) +
  scale_y_continuous(breaks = c(1, 2, 3, 4, 5), trans = t_shift) +
  theme(legend.position="none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=12,color="black"),
        axis.text.y  = element_text(size=12,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        title = element_text(size=16),
        strip.text.x = element_text(size = 14)) +
  coord_cartesian(ylim = c(1,5)) + 
  scale_color_manual(values = myPalette)
```

#### Plot Fig S7
```{r fig.height = 10, fig.width = 8}
AllData$Video = dplyr::recode(AllData$Video,
                       `1` = "Video 01",
                       `2` = "Video 02",
                       `3` = "Video 03",
                       `4` = "Video 04",
                       `5` = "Video 05",
                       `6` = "Video 06",
                       `7` = "Video 07",
                       `8` = "Video 08",
                       `9` = "Video 09",
                       `10` = "Video 10",
                       `11` = "Video 11",
                       `12` = "Video 12",
                       `13` = "Video 13",
                       `14` = "Video 14",
                       `15` = "Video 15",
                       `16` = "Video 16",
                       `17` = "Video 17",
                       `18` = "Video 18",
                       `19` = "Video 19",
                       `20` = "Video 20",
                       `21` = "Video 21",
                       `22` = "Video 22",
                       `23` = "Video 23",
                       `24` = "Video 24")

SubjData = AllData %>% 
  group_by(Subj,Group,Video) %>%
  dplyr::summarise(ChangeRecode = mean(ChangeRecode))

GroupData = SubjData %>%
  group_by(Group,Video) %>%
  dplyr::summarise(meanChangeRecode = mean(ChangeRecode), SE = sem(ChangeRecode))



SubjData$Group = factor(SubjData$Group,levels= c("Liberal", "Conservative"))
GroupData$Group = factor(GroupData$Group, levels= c("Liberal", "Conservative"))

t_shift <- scales::trans_new("shift",
                             transform = function(x) {x-1},
                             inverse = function(x) {x+1})

ggplot(SubjData, aes(x = Group, y = ChangeRecode, color = Group)) +
  geom_bar(aes(x = Group, y = meanChangeRecode),
           data = GroupData,
           stat = "identity",
           fill="white",
           width = 0.25,
           size = 1) +
  geom_errorbar(aes(x = Group, y = NULL, ymin = meanChangeRecode-SE, ymax = meanChangeRecode+SE, color = Group),
                data = GroupData,
                width = 0.2) + 
  geom_jitter(width = 0.05, height = 0, alpha = 0.3) +
  scale_y_continuous(breaks = c(1, 2, 3, 4, 5), trans = t_shift) +
  theme(legend.position="none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=12,color="black"),
        axis.text.y  = element_text(size=12,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        title = element_text(size=16),
        strip.text.x = element_text(size = 12)) +
  coord_cartesian(ylim = c(1,5)) + 
  scale_color_manual(values = myPalette) +
  facet_wrap(~ Video, ncol = 4)
```


#### Neural Polarization Predicts Attitude Change
```{r message=F}
IssueScores = read.csv('../../data/behav/IssueScore.csv') 
colnames(IssueScores) = c('Subj',1,2,3,4,5,6)

IssueScores = IssueScores %>% 
  gather(Issue,ImmScore,2:7)

IssueScores$Subj = factor(IssueScores$Subj)
IssueScores$Issue = as.integer(IssueScores$Issue)

AllData = inner_join(AllData, IssueScores)

# Change
summary(lmer(ChangeRecode ~ Con_Lib + ImmScore + (1|Subj) + (1|Video), data = AllData))

# Agree
summary(lmer(AgreeRecode ~ Con_Lib + ImmScore + (1|Subj) + (1|Video), data = AllData))

# Credible
summary(lmer(CredRecode ~ Con_Lib + ImmScore + (1|Subj) + (1|Video), data = AllData))

```
